# OAuth
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 25908378686-71ksd2bcbiq9ada56ip2p0ve4mdja6d3.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile