# OAuth
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1004323859273-p73a4ok2963b4gmrgg2u32k2kuap6ogc.apps.googleusercontent.com
            clientSecret: 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